### ISSUE TITLE
Spell Tracker

### ISSUE THREAD

**Issue by Ernaldis** [Ernaldis/Player-Aid#1]
==========
Player Aid
-------------
- [ ] Track spells known
- [ ] Track prepared spells
- [ ] Track spell levels
